/*
 * MagicTelecomAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 on 06/20/2016
 */
package com.magictelecom.api;

public class Configuration {
    //The base Uri for API calls
    public static String baseUri = "http://bundles.magictelecom.dev/app_dev.php";

    //API Token
    //TODO: Replace the xAuthToken with an appropriate value
    public static String xAuthToken = "thisismysupperduppersecrettoken";

}
