/*
 * MagicTelecomAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 on 06/20/2016
 */
package com.magictelecom.api.models;

import java.util.*;

public class AccountFormBuilder {
    //the instance to build
    private AccountForm accountForm;

    /**
     * Default constructor to initialize the instance
     */
    public AccountFormBuilder() {
        accountForm = new AccountForm();
    }

    public AccountFormBuilder account(Account account) {
        accountForm.setAccount(account);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public AccountForm build() {
        return accountForm;
    }
}