/*
 * MagicTelecomAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 on 06/20/2016
 */
package com.magictelecom.api.models;

import java.util.*;

public class AccountBuilder {
    //the instance to build
    private Account account;

    /**
     * Default constructor to initialize the instance
     */
    public AccountBuilder() {
        account = new Account();
    }

    public AccountBuilder contactNumber(String contactNumber) {
        account.setContactNumber(contactNumber);
        return this;
    }

    public AccountBuilder email(String email) {
        account.setEmail(email);
        return this;
    }

    public AccountBuilder firstname(String firstname) {
        account.setFirstname(firstname);
        return this;
    }

    public AccountBuilder lastname(String lastname) {
        account.setLastname(lastname);
        return this;
    }

    public AccountBuilder number(String number) {
        account.setNumber(number);
        return this;
    }

    public AccountBuilder roles(List<String> roles) {
        account.setRoles(roles);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Account build() {
        return account;
    }
}