/*
 * MagicTelecomAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 on 06/20/2016
 */
package com.magictelecom.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class AccountForm 
        implements java.io.Serializable {
    private static final long serialVersionUID = 4626451529354900563L;
    private Account account;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("account")
    public Account getAccount ( ) { 
        return this.account;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("account")
    public void setAccount (Account value) { 
        this.account = value;
    }
 
}
 