/*
 * MagicTelecomAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 on 06/20/2016
 */
package com.magictelecom.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class Account 
        implements java.io.Serializable {
    private static final long serialVersionUID = 5260115999009783850L;
    private String contactNumber;
    private String email;
    private String firstname;
    private String lastname;
    private String number;
    private List<String> roles;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("contact_number")
    public String getContactNumber ( ) { 
        return this.contactNumber;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("contact_number")
    public void setContactNumber (String value) { 
        this.contactNumber = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("email")
    public String getEmail ( ) { 
        return this.email;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("email")
    public void setEmail (String value) { 
        this.email = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("firstname")
    public String getFirstname ( ) { 
        return this.firstname;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("firstname")
    public void setFirstname (String value) { 
        this.firstname = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("lastname")
    public String getLastname ( ) { 
        return this.lastname;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("lastname")
    public void setLastname (String value) { 
        this.lastname = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("number")
    public String getNumber ( ) { 
        return this.number;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("number")
    public void setNumber (String value) { 
        this.number = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("roles")
    public List<String> getRoles ( ) { 
        return this.roles;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("roles")
    public void setRoles (List<String> value) { 
        this.roles = value;
    }
 
}
 