/*
 * MagicTelecomAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 on 06/20/2016
 */
package com.magictelecom.api.models;

import java.util.*;

public class CallerLocationFormBuilder {
    //the instance to build
    private CallerLocationForm callerLocationForm;

    /**
     * Default constructor to initialize the instance
     */
    public CallerLocationFormBuilder() {
        callerLocationForm = new CallerLocationForm();
    }

    public CallerLocationFormBuilder callerLocation(CallerLocation callerLocation) {
        callerLocationForm.setCallerLocation(callerLocation);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public CallerLocationForm build() {
        return callerLocationForm;
    }
}