/*
 * MagicTelecomAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 on 06/20/2016
 */
package com.magictelecom.api.models;

import java.util.*;

public class CallerLocationsResponseBuilder {
    //the instance to build
    private CallerLocationsResponse callerLocationsResponse;

    /**
     * Default constructor to initialize the instance
     */
    public CallerLocationsResponseBuilder() {
        callerLocationsResponse = new CallerLocationsResponse();
    }

    public CallerLocationsResponseBuilder code(int code) {
        callerLocationsResponse.setCode(code);
        return this;
    }

    public CallerLocationsResponseBuilder data(Data data) {
        callerLocationsResponse.setData(data);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public CallerLocationsResponse build() {
        return callerLocationsResponse;
    }
}