/*
 * MagicTelecomAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 on 06/20/2016
 */
package com.magictelecom.api.models;

import java.util.*;

public class CallerLocationResponseBuilder {
    //the instance to build
    private CallerLocationResponse callerLocationResponse;

    /**
     * Default constructor to initialize the instance
     */
    public CallerLocationResponseBuilder() {
        callerLocationResponse = new CallerLocationResponse();
    }

    public CallerLocationResponseBuilder code(int code) {
        callerLocationResponse.setCode(code);
        return this;
    }

    public CallerLocationResponseBuilder data(CallerLocation data) {
        callerLocationResponse.setData(data);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public CallerLocationResponse build() {
        return callerLocationResponse;
    }
}