/*
 * MagicTelecomAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 on 06/20/2016
 */
package com.magictelecom.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class CallerLocationForm 
        implements java.io.Serializable {
    private static final long serialVersionUID = 4703590905934533486L;
    private CallerLocation callerLocation;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("caller_location")
    public CallerLocation getCallerLocation ( ) { 
        return this.callerLocation;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("caller_location")
    public void setCallerLocation (CallerLocation value) { 
        this.callerLocation = value;
    }
 
}
 