/*
 * MagicTelecomAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 on 06/20/2016
 */
package com.magictelecom.api.models;

import java.util.*;

public class CartCheckoutFormBuilder {
    //the instance to build
    private CartCheckoutForm cartCheckoutForm;

    /**
     * Default constructor to initialize the instance
     */
    public CartCheckoutFormBuilder() {
        cartCheckoutForm = new CartCheckoutForm();
    }

    public CartCheckoutFormBuilder checkout(Checkout checkout) {
        cartCheckoutForm.setCheckout(checkout);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public CartCheckoutForm build() {
        return cartCheckoutForm;
    }
}