/*
 * MagicTelecomAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 on 06/20/2016
 */
package com.magictelecom.api.models;

import java.util.*;

public class CdrsBuilder {
    //the instance to build
    private Cdrs cdrs;

    /**
     * Default constructor to initialize the instance
     */
    public CdrsBuilder() {
        cdrs = new Cdrs();
    }

    public CdrsBuilder endDate(String endDate) {
        cdrs.setEndDate(endDate);
        return this;
    }

    public CdrsBuilder serviceType(String serviceType) {
        cdrs.setServiceType(serviceType);
        return this;
    }

    public CdrsBuilder startDate(String startDate) {
        cdrs.setStartDate(startDate);
        return this;
    }

    public CdrsBuilder userId(String userId) {
        cdrs.setUserId(userId);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Cdrs build() {
        return cdrs;
    }
}