/*
 * MagicTelecomAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 on 06/20/2016
 */
package com.magictelecom.api.models;

import java.util.*;

public class CheckoutBuilder {
    //the instance to build
    private Checkout checkout;

    /**
     * Default constructor to initialize the instance
     */
    public CheckoutBuilder() {
        checkout = new Checkout();
    }

    public CheckoutBuilder externalOrderReference(String externalOrderReference) {
        checkout.setExternalOrderReference(externalOrderReference);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Checkout build() {
        return checkout;
    }
}