/*
 * MagicTelecomAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 on 06/20/2016
 */
package com.magictelecom.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class Data 
        implements java.io.Serializable {
    private static final long serialVersionUID = 5242899815140704734L;
    private int limit;
    private int page;
    private List<CallerLocation> results;
    private int total;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("limit")
    public int getLimit ( ) { 
        return this.limit;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("limit")
    public void setLimit (int value) { 
        this.limit = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("page")
    public int getPage ( ) { 
        return this.page;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("page")
    public void setPage (int value) { 
        this.page = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("results")
    public List<CallerLocation> getResults ( ) { 
        return this.results;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("results")
    public void setResults (List<CallerLocation> value) { 
        this.results = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("total")
    public int getTotal ( ) { 
        return this.total;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("total")
    public void setTotal (int value) { 
        this.total = value;
    }
 
}
 