/*
 * MagicTelecomAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 on 06/20/2016
 */
package com.magictelecom.api.models;

import java.util.*;

public class DataBuilder {
    //the instance to build
    private Data data;

    /**
     * Default constructor to initialize the instance
     */
    public DataBuilder() {
        data = new Data();
    }

    public DataBuilder limit(int limit) {
        data.setLimit(limit);
        return this;
    }

    public DataBuilder page(int page) {
        data.setPage(page);
        return this;
    }

    public DataBuilder results(List<CallerLocation> results) {
        data.setResults(results);
        return this;
    }

    public DataBuilder total(int total) {
        data.setTotal(total);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Data build() {
        return data;
    }
}