/*
 * MagicTelecomAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 on 06/20/2016
 */
package com.magictelecom.api.models;

import java.util.*;

public class DidItemBuilder 
        extends ItemBuilder {
    //the instance to build
    private DidItem didItem;

    /**
     * Default constructor to initialize the instance
     */
    public DidItemBuilder() {
        didItem = new DidItem();
    }

    public DidItemBuilder callerLocation(CallerLocation callerLocation) {
        didItem.setCallerLocation(callerLocation);
        return this;
    }

    public DidItemBuilder didTypeHandle(String didTypeHandle) {
        didItem.setDidTypeHandle(didTypeHandle);
        return this;
    }

    public DidItemBuilder phoneNumber(String phoneNumber) {
        didItem.setPhoneNumber(phoneNumber);
        return this;
    }

    public DidItemBuilder trunkId(int trunkId) {
        didItem.setTrunkId(trunkId);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public DidItem build() {
        return didItem;
    }
}