/*
 * MagicTelecomAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 on 06/20/2016
 */
package com.magictelecom.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class DidItem 
        extends Item {
    private static final long serialVersionUID = 5399269258210720286L;
    private CallerLocation callerLocation;
    private String didTypeHandle;
    private String phoneNumber;
    private int trunkId;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("_caller_location")
    public CallerLocation getCallerLocation ( ) { 
        return this.callerLocation;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("_caller_location")
    public void setCallerLocation (CallerLocation value) { 
        this.callerLocation = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("did_type_handle")
    public String getDidTypeHandle ( ) { 
        return this.didTypeHandle;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("did_type_handle")
    public void setDidTypeHandle (String value) { 
        this.didTypeHandle = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("phone_number")
    public String getPhoneNumber ( ) { 
        return this.phoneNumber;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("phone_number")
    public void setPhoneNumber (String value) { 
        this.phoneNumber = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("trunk_id")
    public int getTrunkId ( ) { 
        return this.trunkId;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("trunk_id")
    public void setTrunkId (int value) { 
        this.trunkId = value;
    }
 
}
 