/*
 * MagicTelecomAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 on 06/20/2016
 */
package com.magictelecom.api.models;

import java.util.*;

public class ItemBuilder {
    //the instance to build
    private Item item;

    /**
     * Default constructor to initialize the instance
     */
    public ItemBuilder() {
        item = new Item();
    }

    public ItemBuilder itemType(String itemType) {
        item.setItemType(itemType);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Item build() {
        return item;
    }
}