/*
 * MagicTelecomAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 on 06/20/2016
 */
package com.magictelecom.api.models;

import java.util.*;

public class ItemFormBuilder {
    //the instance to build
    private ItemForm itemForm;

    /**
     * Default constructor to initialize the instance
     */
    public ItemFormBuilder() {
        itemForm = new ItemForm();
    }

    public ItemFormBuilder item(Item item) {
        itemForm.setItem(item);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public ItemForm build() {
        return itemForm;
    }
}