/*
 * MagicTelecomAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 on 06/20/2016
 */
package com.magictelecom.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class ItemForm 
        implements java.io.Serializable {
    private static final long serialVersionUID = 4952389171644358937L;
    private Item item;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("item")
    public Item getItem ( ) { 
        return this.item;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("item")
    public void setItem (Item value) { 
        this.item = value;
    }
 
}
 