/*
 * MagicTelecomAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 on 06/20/2016
 */
package com.magictelecom.api.models;

import java.util.*;

public class LocationItemBuilder 
        extends ItemBuilder {
    //the instance to build
    private LocationItem locationItem;

    /**
     * Default constructor to initialize the instance
     */
    public LocationItemBuilder() {
        locationItem = new LocationItem();
    }

    public LocationItemBuilder callerLocation(CallerLocation callerLocation) {
        locationItem.setCallerLocation(callerLocation);
        return this;
    }

    public LocationItemBuilder attributes(String attributes) {
        locationItem.setAttributes(attributes);
        return this;
    }

    public LocationItemBuilder didTypeHandle(String didTypeHandle) {
        locationItem.setDidTypeHandle(didTypeHandle);
        return this;
    }

    public LocationItemBuilder locationHandle(String locationHandle) {
        locationItem.setLocationHandle(locationHandle);
        return this;
    }

    public LocationItemBuilder quantity(int quantity) {
        locationItem.setQuantity(quantity);
        return this;
    }

    public LocationItemBuilder trunkId(int trunkId) {
        locationItem.setTrunkId(trunkId);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public LocationItem build() {
        return locationItem;
    }
}