/*
 * MagicTelecomAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 on 06/20/2016
 */
package com.magictelecom.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class LocationItem 
        extends Item {
    private static final long serialVersionUID = 5742475194370133307L;
    private CallerLocation callerLocation;
    private String attributes;
    private String didTypeHandle;
    private String locationHandle;
    private int quantity;
    private int trunkId;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("_caller_location")
    public CallerLocation getCallerLocation ( ) { 
        return this.callerLocation;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("_caller_location")
    public void setCallerLocation (CallerLocation value) { 
        this.callerLocation = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("attributes")
    public String getAttributes ( ) { 
        return this.attributes;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("attributes")
    public void setAttributes (String value) { 
        this.attributes = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("did_type_handle")
    public String getDidTypeHandle ( ) { 
        return this.didTypeHandle;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("did_type_handle")
    public void setDidTypeHandle (String value) { 
        this.didTypeHandle = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("location_handle")
    public String getLocationHandle ( ) { 
        return this.locationHandle;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("location_handle")
    public void setLocationHandle (String value) { 
        this.locationHandle = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("quantity")
    public int getQuantity ( ) { 
        return this.quantity;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("quantity")
    public void setQuantity (int value) { 
        this.quantity = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("trunk_id")
    public int getTrunkId ( ) { 
        return this.trunkId;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("trunk_id")
    public void setTrunkId (int value) { 
        this.trunkId = value;
    }
 
}
 