/*
 * MagicTelecomAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 on 06/20/2016
 */
package com.magictelecom.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class RoutingBase 
        implements java.io.Serializable {
    private static final long serialVersionUID = 5630883911040151980L;
    private List<Endpoint> endpoints;
    private String logic;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("endpoints")
    public List<Endpoint> getEndpoints ( ) { 
        return this.endpoints;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("endpoints")
    public void setEndpoints (List<Endpoint> value) { 
        this.endpoints = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("logic")
    public String getLogic ( ) { 
        return this.logic;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("logic")
    public void setLogic (String value) { 
        this.logic = value;
    }
 
}
 