/*
 * MagicTelecomAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 on 06/20/2016
 */
package com.magictelecom.api.models;

import java.util.*;

public class RoutingBaseBuilder {
    //the instance to build
    private RoutingBase routingBase;

    /**
     * Default constructor to initialize the instance
     */
    public RoutingBaseBuilder() {
        routingBase = new RoutingBase();
    }

    public RoutingBaseBuilder endpoints(List<Endpoint> endpoints) {
        routingBase.setEndpoints(endpoints);
        return this;
    }

    public RoutingBaseBuilder logic(String logic) {
        routingBase.setLogic(logic);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public RoutingBase build() {
        return routingBase;
    }
}