/*
 * MagicTelecomAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 on 06/20/2016
 */
package com.magictelecom.api.models;

import java.util.*;

public class TelephoneNumberBuilder {
    //the instance to build
    private TelephoneNumber telephoneNumber;

    /**
     * Default constructor to initialize the instance
     */
    public TelephoneNumberBuilder() {
        telephoneNumber = new TelephoneNumber();
    }

    public TelephoneNumberBuilder routing(RoutingBase routing) {
        telephoneNumber.setRouting(routing);
        return this;
    }

    public TelephoneNumberBuilder alias(String alias) {
        telephoneNumber.setAlias(alias);
        return this;
    }

    public TelephoneNumberBuilder channels(int channels) {
        telephoneNumber.setChannels(channels);
        return this;
    }

    public TelephoneNumberBuilder sipEndPointUri(String sipEndPointUri) {
        telephoneNumber.setSipEndPointUri(sipEndPointUri);
        return this;
    }

    public TelephoneNumberBuilder trunkId(int trunkId) {
        telephoneNumber.setTrunkId(trunkId);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public TelephoneNumber build() {
        return telephoneNumber;
    }
}