/*
 * MagicTelecomAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 on 06/20/2016
 */
package com.magictelecom.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class TelephoneNumberForm 
        implements java.io.Serializable {
    private static final long serialVersionUID = 4687379671515517670L;
    private TelephoneNumber telephoneNumber;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("telephone_number")
    public TelephoneNumber getTelephoneNumber ( ) { 
        return this.telephoneNumber;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("telephone_number")
    public void setTelephoneNumber (TelephoneNumber value) { 
        this.telephoneNumber = value;
    }
 
}
 