/*
 * MagicTelecomAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 on 06/20/2016
 */
package com.magictelecom.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class TelephoneNumber 
        implements java.io.Serializable {
    private static final long serialVersionUID = 5035007577795773373L;
    private RoutingBase routing;
    private String alias;
    private int channels;
    private String sipEndPointUri;
    private int trunkId;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("_routing")
    public RoutingBase getRouting ( ) { 
        return this.routing;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("_routing")
    public void setRouting (RoutingBase value) { 
        this.routing = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("alias")
    public String getAlias ( ) { 
        return this.alias;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("alias")
    public void setAlias (String value) { 
        this.alias = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("channels")
    public int getChannels ( ) { 
        return this.channels;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("channels")
    public void setChannels (int value) { 
        this.channels = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("sip_end_point_uri")
    public String getSipEndPointUri ( ) { 
        return this.sipEndPointUri;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("sip_end_point_uri")
    public void setSipEndPointUri (String value) { 
        this.sipEndPointUri = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("trunk_id")
    public int getTrunkId ( ) { 
        return this.trunkId;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("trunk_id")
    public void setTrunkId (int value) { 
        this.trunkId = value;
    }
 
}
 