/*
 * MagicTelecomAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 on 06/20/2016
 */
package com.magictelecom.api.models;

import java.util.*;

public class TelephoneNumberFormBuilder {
    //the instance to build
    private TelephoneNumberForm telephoneNumberForm;

    /**
     * Default constructor to initialize the instance
     */
    public TelephoneNumberFormBuilder() {
        telephoneNumberForm = new TelephoneNumberForm();
    }

    public TelephoneNumberFormBuilder telephoneNumber(TelephoneNumber telephoneNumber) {
        telephoneNumberForm.setTelephoneNumber(telephoneNumber);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public TelephoneNumberForm build() {
        return telephoneNumberForm;
    }
}