/*
 * MagicTelecomAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 on 06/20/2016
 */
package com.magictelecom.api.models;

import java.util.*;

public class TokenFormBuilder {
    //the instance to build
    private TokenForm tokenForm;

    /**
     * Default constructor to initialize the instance
     */
    public TokenFormBuilder() {
        tokenForm = new TokenForm();
    }

    public TokenFormBuilder token(Token token) {
        tokenForm.setToken(token);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public TokenForm build() {
        return tokenForm;
    }
}