/*
 * MagicTelecomAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 on 06/20/2016
 */
package com.magictelecom.api.models;

import java.util.*;

public class TokenBuilder {
    //the instance to build
    private Token token;

    /**
     * Default constructor to initialize the instance
     */
    public TokenBuilder() {
        token = new Token();
    }

    public TokenBuilder isActive(boolean isActive) {
        token.setIsActive(isActive);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Token build() {
        return token;
    }
}